340 separate ds auth from sign in and store auth token
corpus-ventures/dm3 pull request #348
Opened 2022-11-25 14:56 UTC by AlexNi245

2022-11-29 08:52 UTC, AlexNi245 commented on packages/lib/src/session/signInWithEtheruem.ts
> +        issuedAt: new Date(12).getTime().toString(),
How should we implement issuedAt ? If we are doing it properly it'll no longer possible to create the encryption key in an deterministic way

2022-11-30 15:35 UTC, hai-ko requested changes

2022-11-30 15:35 UTC, hai-ko commented on packages/lib/src/session/SignIn/signProfile.ts
> +        console.log(e);
remove `console.log`

2022-11-30 15:35 UTC, hai-ko commented on packages/react/src/sign-in/Connectors.ts
> +    console.log('Auth state', state.auth);
remove `console.log`

2022-11-30 15:35 UTC, hai-ko commented on packages/react/src/ui-shared/RequestContacts.ts
> +    console.log('GOT CONTRACT ', retrievedContacts);
remove `console.log`

2022-11-30 16:14 UTC, hai-ko approved these changes

2022-11-30 17:48 UTC, merged